### ISSUE TITLE
About the Processed dataset

### ISSUE THREAD

**Issue by dummerchen** [lilygeorgescu/MHCA#1]
I'm impressed by your work but the original IXI datasets on the official website is not the same as that described in the paper. Can you provide the processed data or processing code?

**Comment by lilygeorgescu** [comment]
Hi,

Thank you for your interest in our work.

We use the same data set settings as Zhao et al. and Zhang et al. ([49, 50] in the paper).  

This is taken from [49]: 
"The processed datasets are available at: https://pan.baidu.com/s/1Ak3GiJk5H1Pdn3igzElb7w (kn3d)".

Please download the data set provided by the aforementioned authors.

Best.
Lili
Best,
Iuliana Georgescu
