### ISSUE TITLE
How to inference multi input？

### ISSUE THREAD

**Issue by dummerchen** [lilygeorgescu/MHCA#3]
When I use multi input , it is wrong. 

'While copying the parameter named spatial_attention.0.weight, whose dimensions in the model are torch.Size([128, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([256, 128, 3, 3]).'

I guess the nfeat number is wrong and I try to change it from 64 to 128.

'unexpected key "head_n.0.weight" in state_dict'

I use the strict False.  

TypeError: conv2d() received an invalid combination of arguments - got (list, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!list!, !Parameter!, !Parameter!, !tuple!, !tuple!, !tuple!, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!list!, !Parameter!, !Parameter!, !tuple!, !tuple!, !tuple!, int)

Could you please release the option of multi input ?
Here are my options.
(python run.py --model EDSR --scale 4  --use_nav True --n_resblocks 16 \
     --n_feats 128 --res_scale 0.1 --shift_mean=False \
     --use_attention_resblock --use_mhca_3 --ratio=0.5 \
     --pre_train=pretrained_models/model_multi_input_IXI_x4.pt

**Comment by lilygeorgescu** [comment]
Hi,

Thank you for your interest in our work.

Please use the command options that we released in order to get the inference results.

For multi-input scale 4, this is the command:
```
python run.py --model EDSR_Nav --scale 4  --n_resblocks 16 --n_feats 64 --res_scale 0.1  \
 --shift_mean=False --use_nav --use_mhca_2 --ratio=0.5  --pre_train=pretrained_models/model_multi_input_IXI_x4.pt
```
```n_feats``` parameters is set correctly, it should not be changed.
What is not ok in your command is ```--model EDSR``` instead of ```--model EDSR_Nav``` which is the model that takes multiple inputs.

Best,
Lili

**Comment by dummerchen** [comment]
I use the same options to inference but the sample results are not as good as expected. Could you please provide a sample result?

**Comment by dummerchen** [comment]
Thanks for your reply, I have got the correct result. But because it's pixel value is not in 0~255, I don't know how to calculate psnr. Can you provide the data processing code before calculating psnr?
