### ISSUE TITLE
how to achieve the results of experiment？

### ISSUE THREAD

**Issue by mountaincode1** [lilygeorgescu/MHCA#5]
Congratulations on your excellent creativity and SOTA results. When I wanted to achieve the results in the paper, I didn't know the parameters of the RDN model. I set D=16, C=8, G=64, but couldn't achieve psnr=38.75. How should I set it? Thank you for your answers!

**Comment by lilygeorgescu** [comment]
Hi,

We did not use RDN architecture in our work. We used EDSR and the hyperparameters values are shown in run.py.

Best
