### ISSUE TITLE
Ask For Link Of Datasets

### ISSUE THREAD

**Issue by MeycL** [lilygeorgescu/MHCA#6]
Thank you very much for your excellent work. May I ask if you could provide the preprocessed datasets for NAMIC Brain Multimodality and Coltea-Lung-CT-100W?

**Comment by lilygeorgescu** [comment]
Hi,

You can download the Coltea-lung-CT from here: https://github.com/ristea/cycle-transformer
Unfortunately, the NAMIC data set is not available online anymore.

Lili
